version: '3.8'
services:
  # 1. 데이터 저장소 (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: smart-farm-db
    environment:
      - POSTGRES_USER=${DB_USER}       
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # 2. 데이터 워크플로우 (Airflow)
  airflow:
    image: apache/airflow:2.7.1
    container_name: smart-farm-airflow
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://tae_tae:smartfarm@postgres/agriculture
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      # 필요한 모든 라이브러리를 한 줄로 통합했습니다.
      - _PIP_ADDITIONAL_REQUIREMENTS=scikit-learn pandas requests sqlalchemy psycopg2-binary python-dotenv
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./.env:/opt/airflow/.env
    command: standalone
